### ISSUE TITLE
Apply robots.txt, sitemap for SEO

### ISSUE THREAD

**Issue by congaweb** [team-GIFT/gift#135]
**Todo**

- [x] robots.txt
- [x] sitemap

**ETC**

- Opinions & Problems

**Comment by congaweb** [comment]
@sosoYim @jkpark104 

public 폴더는 깃에 올라가지 않는 관계로, 파일 여기에 올려드릴게요!
각자 본인 환경 public 폴더
[robots.zip](https://github.com/team-GIFT/gift/files/7948377/robots.zip)
에 넣어주세요 :

**Comment by sosoYim** [comment]
감사합니다~
