### ISSUE TITLE
good first component 제작

### ISSUE THREAD

**Issue by congaweb** [team-GIFT/gift#15]
**Todo**

- [x] types
- [x] styled-component
- [x] React component
- [x] Storybook

**Assignee**

- @sosoYim @congaweb @jkpark104 

**ETC**

- good first component는 컴포넌트 제작 시 기준이 됩니다.
- 컴포넌트 제작 시 주의사항이 있다면 댓글로 남겨주세요.
- Storybook docs에 명세를 같이 명시해주세요.

**Comment by sosoYim** [comment]
Card 컴퍼넌트를 참고하시면 됩니다!
